[package]
name = "chess_ai_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
# Macroquad 0.4.10 without any extra features
macroquad = "0.4.10"
# web-sys pinned to what Macroquad 0.4.10 used, with console logging enabled
web-sys   = { version = "0.3.69", features = ["console"] }
# Your other deps
chess        = "3.2.0"
wasm-bindgen = "=0.2.100"

[profile.release]
opt-level = "z"
lto       = true
